steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/indigo-skyline-463722-s0/aiventory-repo/aiventory-agent",
        "."
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/indigo-skyline-463722-s0/aiventory-repo/aiventory-agent"
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "aiventory-agent",
        "--image",
        "us-central1-docker.pkg.dev/indigo-skyline-463722-s0/aiventory-repo/aiventory-agent",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated"
      ]
      
options:
  logging: CLOUD_LOGGING_ONLY